import asyncio
import os
import shutil
import uuid

from dotenv import load_dotenv
from temporalio import activity
from temporalio.exceptions import ApplicationError

from bwb.scheduling_service.executors.generic import cmd_no_output, run_container_cmd, setup_volumes, \
    get_container_cmd, container_to_host_path, get_remote_fs, container_to_remote_path, download_and_heartbeat, \
    upload_and_heartbeat
from bwb.scheduling_service.scheduler_types import SetupVolumesParams, ContainerCmdParams, CmdOutput, \
    DownloadFileDepsParams, SyncDirParams
from typing import Dict, Optional


# Function to create directories used as singularity volumes.
@activity.defn
async def setup_volumes_on_worker(params: SetupVolumesParams) -> dict:
    bucket_id = params.bucket_id

    load_dotenv()
    storage_dir = os.getenv("SCHED_STORAGE_DIR")

    workflow_dir = os.path.join(storage_dir, bucket_id)
    os.makedirs(workflow_dir, exist_ok=True)

    # Following three are mapped to /tmp, /data/, and /root, respectively.
    os.makedirs(os.path.join(workflow_dir, "singularity_tmp", "output"), exist_ok=True)
    os.makedirs(os.path.join(workflow_dir, "singularity_data"), exist_ok=True)
    os.makedirs(os.path.join(workflow_dir, "singularity_root"), exist_ok=True)

    # This will be mapped as "." The hack here is that "bwb_run_dir"
    # is assumed to be the same directory mapped to /data in the
    # BWB container, meaning that the files generated by temporal
    # will be visible from within BWB. In the long-term, this needs
    # to be replaced with some sort of distributed file system.
    os.makedirs(os.path.join(workflow_dir, "bwb_run_dir"), exist_ok=True)

    return {
        "/tmp": os.path.join(workflow_dir, "singularity_tmp"),
        "/data": os.path.join(workflow_dir, "singularity_data"),
        "/root": os.path.join(workflow_dir, "singularity_root"),
    }


# Function to read every file in container's /tmp/output,
# returning dictionary of key-value pairs in which key
# is filename and value is the file's contents. This
# is how BWB containers express outputs.
async def get_container_outputs(cnt: str, volumes: dict, use_singularity: bool) -> Optional[Dict[str, str]]:
    outputs = {}
    ls_output = ""
    cnt_name = cnt
    commit_image = str(uuid.uuid4())

    async def cleanup():
        if not use_singularity:
            await cmd_no_output(f"docker rmi {commit_image}")

    if not use_singularity:
        await cmd_no_output(f"docker commit {cnt} {commit_image}")
        cnt_name = commit_image

    ls_output = await run_container_cmd(
        cnt_name, "ls /tmp/output",
        volumes=volumes,
        use_singularity=use_singularity,
        override_ept=True,
    )

    if ls_output is None:
        await cleanup()
        raise ApplicationError(f"Getting outputs from {commit_image} failed")
    if ls_output == "":
        await cleanup()
        return {}

    outfiles = ls_output.strip().split('\n')
    for outfile in outfiles:
        output = await run_container_cmd(
            cnt_name, f"cat /tmp/output/{outfile}",
            volumes=volumes, use_singularity=use_singularity, override_ept=True)
        if output is None:
            return None
        outputs[outfile] = output.rstrip('\n')

    await cleanup()
    return outputs


# Activity to run a singularity command on a specified, pre-existing
# SIF. (I.e. must run after the build_singularity_img activity.)
@activity.defn
async def run_workflow_cmd(cmd_obj: ContainerCmdParams) -> CmdOutput:
    async def heartbeat():
        while True:
            await asyncio.sleep(40)
            activity.heartbeat()

    async def rm_container():
        if not cmd_obj.use_singularity:
            await cmd_no_output(f"docker rm {cnt_name}")

    heartbeat_task = asyncio.create_task((heartbeat()))
    try:
        volumes = await setup_volumes(cmd_obj.bucket_id)
        cnt_name = str(uuid.uuid4())
        volumes["/tmp"] = os.path.join(volumes["/tmp"], cnt_name)
        os.makedirs(os.path.join(volumes["/tmp"], "output"))
        # First argument is empty, because cmd_obj.cmd already contains image name.
        # TODO: cleanup, this is confusing.
        con_cmd = get_container_cmd(
            "",
            cmd_obj.cmd,
            volumes=volumes,
            use_singularity=cmd_obj.use_singularity,
            use_gpu=cmd_obj.use_gpu,
            show_cmd=True,
            rm=False,
            name=cnt_name
        )
        print(con_cmd)
        result = await cmd_no_output(con_cmd)

        if result is None:
            await rm_container()
            shutil.rmtree(volumes["/tmp"])
            raise ApplicationError(f"Failed command {con_cmd}")

        outputs_cnt = cmd_obj.image if cmd_obj.use_singularity else cnt_name
        outputs = await get_container_outputs(
            outputs_cnt, volumes=volumes, use_singularity=cmd_obj.use_singularity)

        # After executing long singularity commands, it can take some
        # time for changes to the container filesystem to propagate onto
        # the host filesystem. (See [https://github.com/nextflow-io/nextflow/discussions/4272]).
        # This can result in errors reading the outputs from the container's
        # /tmp/output, so it is a good idea to repeatedly wait and retry.
        attempt = 1
        while outputs is None and attempt < 5:
            await asyncio.sleep(4**attempt)
            outputs = await get_container_outputs(
                outputs_cnt, volumes=volumes, use_singularity=cmd_obj.use_singularity)
            attempt += 1

        if outputs is None:
            # For debug reasons, we don't delete the /tmp mount.
            # Should probably change this for production version.
            raise ApplicationError(f"Failed reading outputs from {volumes['/tmp']}")

        output_files = cmd_obj.cmd_files.output_files
        for out_key, out_val in outputs.items():
            if out_key in output_files:
                if isinstance(out_val, list):
                    output_files[out_key] |= set(out_val)
                else:
                    output_files[out_key].add(out_val)

        for del_key, del_set in cmd_obj.cmd_files.deletable.items():
            for filename in del_set:
                host_path = container_to_host_path(filename, volumes)
                if os.path.isfile(host_path):
                    print(f"Deleting file {del_key} = {filename}")
                    os.remove(host_path)
                elif os.path.isdir(host_path):
                    print(f"Deleting dir {del_key} = {filename}")
                    shutil.rmdir(host_path)
                else:
                    print(f"Deletable file {del_key} = {filename} not found")

        await rm_container()
        heartbeat_task.cancel()

        return CmdOutput(
            success=True,
            logs=result,
            outputs=outputs,
            output_files=output_files,
        )
    except asyncio.exceptions.CancelledError:
        heartbeat_task.cancel()
        raise


# Activity to download all files needed to execute the command of
# a particular activity. Make sure to route this to the same host
# as the command itself.
@activity.defn
async def download_file_deps(params: DownloadFileDepsParams):
    cmd_files = params.cmd_files
    bucket_id = params.bucket_id
    remote_fs = get_remote_fs()

    volumes = await setup_volumes(bucket_id)

    for key, file_set in cmd_files.input_files.items():
        for file in file_set:
            local_path = container_to_host_path(file, volumes)
            remote_path = container_to_remote_path(file, bucket_id)
            await download_and_heartbeat(local_path, remote_path, remote_fs)

    # If using singularity, download the relevant SIF
    # file to image directory.
    sif_basename = params.sif_path
    if sif_basename is not None:
        load_dotenv()
        storage_dir = os.getenv("SCHED_STORAGE_DIR")
        local_sif_path = os.path.join(storage_dir, "images", sif_basename)
        remote_sif_path = os.path.join(bucket_id, "images", sif_basename)
        await download_and_heartbeat(local_sif_path, remote_sif_path, remote_fs)


# Ensure that all files which exist in params.local_path
# but not in params.remote_path are uploaded to Minio instance.
@activity.defn
async def sync_dir(params: SyncDirParams):
    output_files = params.output_files
    bucket_id = params.bucket_id
    volumes = await setup_volumes(bucket_id)

    remote_fs = get_remote_fs()

    for key, file_list in output_files.items():
        for file in file_list:
            local_file = container_to_host_path(file, volumes)
            remote_file = container_to_remote_path(file, bucket_id)
            await upload_and_heartbeat(local_file, remote_file, remote_fs)
